#!/bin/bash

export HERE="$(dirname "$(readlink -f "${0}")")"

#---------------------------------------------------------------------------

OPTION="${1}"
shift

#---------------------------------------------------------------------------

APPIMAGE_DIR=$(dirname "${APPIMAGE}")

[ "${APPIMAGE_DIR}" = "${PWD}" ] && {
  export APPIMAGE="./"$(basename "${APPIMAGE}")
}

#---------------------------------------------------------------------------

. ${HERE}/BottleTool.sh
. ${HERE}/AppDirTool.sh
. ${HERE}/FlagsTool.sh
. ${HERE}/Help.sh
. ${HERE}/Recipe.sh

#---------------------------------------------------------------------------

[ "${OPTION}" = "--recipe" ] && {
  [ ! -f "${1}" ] && {
    echo "Error: Recipe file '${1}' not found"
    exit 1
  }
  recipe.run "${1}"
  exit ${?}
}

#---------------------------------------------------------------------------

[ -z "${BOTTLE_NAME}" ] && {
  export BOTTLE_NAME="$(echo ${1} | sed 's/[[:space:]]//g')"
  shift
}

#---------------------------------------------------------------------------

type bottle.${OPTION} &> /dev/null && {
  bottle.${OPTION} "${1}" "${2}"
  exit ${?}
}

type flags.${OPTION} &> /dev/null && {
  flags.${OPTION} "${1}"
  exit ${?}
}

type appdir.${OPTION} &> /dev/null && {
  appdir.${OPTION} "${1}"
  exit ${?}
}

help.main

[ "${OPTION}" = "--help" ] && exit 0 || exit 1
