#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"

export LD_LIBRARY_PATH="${HERE}/usr/lib":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/lib":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/lib/i386-linux-gnu":${LD_LIBRARY_PATH}

#Sound Library
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu/pulseaudio":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu/alsa-lib":${LD_LIBRARY_PATH}

#Font Config
export FONTCONFIG_PATH="${HERE}/etc/fonts"

#LD
export WINELDLIBRARY="${HERE}/lib/ld-linux.so.2"

#Winetricks
export WINE="${HERE}/AppRun"
export WINESERVER="$(which echo)"

#Cabextract
export PATH="${HERE}/bin:$PATH"

if [ "$1" == "winetricks" ]; then
  shift
  "${HERE}/bin/winetricks" ${@}
  exit $?
fi

#Copy ld-linux.so.2 to host
cp -L "${HERE}/lib/ld-linux.so.2" /tmp

#Wine
"$HERE/bin/wine" "$@" 2>&1 | cat | grep -v ":fixme:"
