#!/bin/bash

function cleanup() {
  if [ -d "${WINEPREFIX}/drive_c" ]; then
    find "${WINEPREFIX}/drive_c" -maxdepth 1 -type l | sed 's|^|unlink "|' | sed 's|$|"|' |  sh
  fi
  if [ -f "${WINEPREFIX}/.update-timestamp" ]; then
    echo "disabled" > "${WINEPREFIX}/.update-timestamp"
  fi
}

export HERE="$(dirname "$(readlink -f "${0}")")"
export APP_ID=$(basename -s .desktop $(ls "${HERE}/"*".desktop"))
export APP_PATH=$(cat "${HERE}/${APP_ID}.desktop" | grep ^"X-WineExec=" | cut -c 13- | sed 's/.$//')
export WINEPREFIX="${XDG_CONFIG_HOME}/${APP_ID}"
export APP_FILES=$(find "${HERE}/app" -maxdepth 1 | sed '1d')
export LD_LIBRARY_PATH="${HERE}/usr/lib":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/lib":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/lib/i386-linux-gnu":${LD_LIBRARY_PATH}
export LIBGL_DRIVERS_PATH="${HERE}/usr/lib/i386-linux-gnu/dri"
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu/pulseaudio":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu/alsa-lib":${LD_LIBRARY_PATH}
export FONTCONFIG_PATH="${HERE}/etc/fonts"
export WINELDLIBRARY="${HERE}/lib/ld-linux.so.2"
export LD_PRELOAD="${HERE}/bin/libhookexecv.so" 

mkdir -p "${WINEPREFIX}/drive_c"

trap cleanup EXIT
     cleanup

if [ "$(cat ${HERE}/copy_app_files)" == "yes" ]; then
  if [ ! -f "${WINEPREFIX}/already_copied" ]; then
    echo "${APP_FILES}" | grep -v "windows"$ | sed "s/^/cp -vr \"/g" | sed "s|$|\" ${WINEPREFIX}/drive_c|" | sh
    touch "${WINEPREFIX}/already_copied"
  fi
  export APP_FILES=$(echo "${APP_FILES}" | grep "windows"$)
fi

echo "${APP_FILES}" | sed "s|^|ln -s \"|" | sed "s|$|\" ${WINEPREFIX}/drive_c|" | sh

if [ ! -f "${WINEPREFIX}/system.reg" ]; then
  export TODAY="$(date '+%Y%m%d')"
  cp "${HERE}/improve.reg" "${WINEPREFIX}/default.reg"
  sed -i "s/{Install date here}/\"InstallDate\"=\"${TODAY}\"/g" "${WINEPREFIX}/default.reg"
  "${HERE}/wine" create-register "${WINEPREFIX}/default.reg"
fi

LD_PRELOAD="${HERE}/bin/libhookexecv.so" "${WINELDLIBRARY}" "${HERE}/bin/wine" "${APP_PATH}" ${*} 2>&1 | grep -v ":fixme:"

