#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"

export LD_LIBRARY_PATH="${HERE}/usr/lib":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/lib":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/lib/i386-linux-gnu":${LD_LIBRARY_PATH}

# Fix libgl error failed to load driver swrast
export LIBGL_DRIVERS_PATH="${HERE}/usr/lib/i386-linux-gnu/dri"

#Sound Library
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu/pulseaudio":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu/alsa-lib":${LD_LIBRARY_PATH}

#Font Config
export FONTCONFIG_PATH="${HERE}/etc/fonts"

#Winetricks
if [ "$1" == "winetricks" ]; then
  shift
  export WINE="${HERE}/wine"
  export WINESERVER="$(which echo)"
  export PATH="$PATH:${HERE}/bin"
  "${HERE}/bin/winetricks" ${@}
  exit $?
fi

#LD
export WINELDLIBRARY="${HERE}/lib/ld-linux.so.2"
export LD_PRELOAD="${HERE}/bin/libhookexecv.so" 

#Wine

if [ "$1" == "create-register" ]; then
  shift
  "${WINELDLIBRARY}" "${HERE}/bin/wine" regedit "${*}"
  exit $?
fi

if [ "$1" == "regedit" ]; then
  shift
  option="${1}"
  if [ "${option}" == "" ]; then
    "${WINELDLIBRARY}" "${HERE}/bin/wine" regedit > /dev/null
    exit ${?}
  fi
  shift
  "${WINELDLIBRARY}" "${HERE}/bin/wine" regedit "${option}" "${*}"
  exit $?
fi

if [ "$1" == "--run" ]; then
  "${WINELDLIBRARY}" "${HERE}/bin/wine" "${*}" 2>&1 | grep -v ":fixme:" > /dev/null
  exit $?
fi

"${WINELDLIBRARY}" "${HERE}/bin/wine" "${*}" 2>&1 | grep -v ":fixme:"
exit $?







