#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"

export LD_LIBRARY_PATH="${HERE}/usr/lib":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/lib":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/lib/i386-linux-gnu":${LD_LIBRARY_PATH}

# Fix libgl error failed to load driver swrast
export LIBGL_DRIVERS_PATH="${HERE}/usr/lib/i386-linux-gnu/dri"

#Sound Library
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu/pulseaudio":${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH="${HERE}/usr/lib/i386-linux-gnu/alsa-lib":${LD_LIBRARY_PATH}

#Font Config
export FONTCONFIG_PATH="${HERE}/etc/fonts"

#Winetricks
if [ "$1" == "winetricks" ]; then
  shift
  export WINE="${HERE}/wine"
  export WINESERVER="$(which echo)"
  export PATH="$PATH:${HERE}/bin"
  "${HERE}/bin/winetricks" ${@}
  exit $?
fi

#LD
export WINELDLIBRARY="${HERE}/lib/ld-linux.so.2"

#Wine

[ "${WINEDEBUG}" = "+file" ] && {
  LD_PRELOAD="${HERE}/bin/libhookexecv.so" strace -e file -o "${HERE}/used_files" "${WINELDLIBRARY}" "${HERE}/bin/wine" "${1}" "${2}" 2>&1 | grep -v ":fixme:"
  exit $?
}

LD_PRELOAD="${HERE}/bin/libhookexecv.so" "${WINELDLIBRARY}" "${HERE}/bin/wine" "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" 2>&1 | grep -v ":fixme:"
exit $?

